//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitor.ConsoleRunner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SerializedEvents {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SerializedEvents() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monitor.ConsoleRunner.SerializedEvents", typeof(SerializedEvents).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:&quot;354c35b0-dc25-4853-a4aa-77979d5bcf73&quot;,&quot;Title&quot;:&quot;Recurring&quot;,&quot;EventCategory&quot;:{&quot;Id&quot;:&quot;88d9e8ea-87fc-499b-9b9b-4503c306d0bb&quot;,&quot;Name&quot;:&quot;Payment&quot;}},{&quot;Id&quot;:&quot;aac23b84-420b-448b-a6c3-bb869acfa1bf&quot;,&quot;Title&quot;:&quot;Non-Recurring&quot;,&quot;EventCategory&quot;:{&quot;Id&quot;:&quot;88d9e8ea-87fc-499b-9b9b-4503c306d0bb&quot;,&quot;Name&quot;:&quot;Payment&quot;}},{&quot;Id&quot;:&quot;050075d6-c5af-487d-a978-c9d9ea8f929e&quot;,&quot;Title&quot;:&quot;Non-Recurring&quot;,&quot;EventCategory&quot;:{&quot;Id&quot;:&quot;88d9e8ea-87fc-499b-9b9b-4503c306d0bb&quot;,&quot;Name&quot;:&quot;Payment&quot;}},{&quot;Id&quot;:&quot;b698b350-6c4f-493b-b1a7-5b92f08834b8&quot;,&quot;Title&quot;:&quot;Recurring&quot;,&quot;Ev [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:&quot;c620d513-b070-40c4-a798-fec1edb284ed&quot;,&quot;Title&quot;:&quot;Authentication Failure&quot;,&quot;EventCategory&quot;:{&quot;Id&quot;:&quot;a267720d-4703-4de0-9f38-1b7770310114&quot;,&quot;Name&quot;:&quot;Website Error&quot;}},{&quot;Id&quot;:&quot;9dddbdc1-f0d8-44ea-99d5-f90a1ed8dff2&quot;,&quot;Title&quot;:&quot;Db Timeout&quot;,&quot;EventCategory&quot;:{&quot;Id&quot;:&quot;a267720d-4703-4de0-9f38-1b7770310114&quot;,&quot;Name&quot;:&quot;Website Error&quot;}},{&quot;Id&quot;:&quot;7dcbfc7c-0f9b-4efa-8ba0-245d198bf482&quot;,&quot;Title&quot;:&quot;Db Timeout&quot;,&quot;EventCategory&quot;:{&quot;Id&quot;:&quot;a267720d-4703-4de0-9f38-1b7770310114&quot;,&quot;Name&quot;:&quot;Website Error&quot;}},{&quot;Id&quot;:&quot;122d0d9b-07b9-4de0-9ea5-d608dfc1f270 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebsiteErrors {
            get {
                return ResourceManager.GetString("WebsiteErrors", resourceCulture);
            }
        }
    }
}
