//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitor.ConsoleRunner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SerializedEvents {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SerializedEvents() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monitor.ConsoleRunner.SerializedEvents", typeof(SerializedEvents).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:&quot;279f6710-5aae-4d30-9b0a-8ecfb9a04421&quot;,&quot;Title&quot;:&quot;DB Timeout&quot;,&quot;EventCategory&quot;:{&quot;Id&quot;:&quot;039174d3-86f1-47c5-8baf-717b233119e1&quot;,&quot;Name&quot;:&quot;Website Error&quot;}},{&quot;Id&quot;:&quot;5336ca90-ad1d-4d00-b31b-64637b0dcf90&quot;,&quot;Title&quot;:&quot;DB Timeout&quot;,&quot;EventCategory&quot;:{&quot;Id&quot;:&quot;039174d3-86f1-47c5-8baf-717b233119e1&quot;,&quot;Name&quot;:&quot;Website Error&quot;}},{&quot;Id&quot;:&quot;f0c19aed-59d1-442a-a595-f3ce1e6321c7&quot;,&quot;Title&quot;:&quot;DB Timeout&quot;,&quot;EventCategory&quot;:{&quot;Id&quot;:&quot;039174d3-86f1-47c5-8baf-717b233119e1&quot;,&quot;Name&quot;:&quot;Website Error&quot;}},{&quot;Id&quot;:&quot;ba3900f3-dd7e-42de-b251-eff984702709&quot;,&quot;Title&quot;:&quot;D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebsiteErrors {
            get {
                return ResourceManager.GetString("WebsiteErrors", resourceCulture);
            }
        }
    }
}
